### ISSUE TITLE
日本語が画像に表示されない

### ISSUE THREAD

**Issue by shuma1020** [shuma1020/twitter_api#7]
@ms2sato 
[この](https://qiita.com/isotai/items/4fdc4884ff74ce3de7f4)記事と同じ症状です。用いるフォントは日本語に対応しているGenEiGothicN-U-KLでapp/.fontsにあります。アルファベットは表示させることができます。

aaaaの上に実はあああああと日本語で入力しています。しかし表示されません。

<img width="392" alt="スクリーンショット 2020-02-05 22 30 20 1" src="https://user-images.githubusercontent.com/56459339/73846038-218de480-4867-11ea-82dc-9a4acf06c70f.png">

ログを確認してみると下記のような指摘が出ていた。
フォントが読み込めていない模様
```
mogrify: unable to read font `.fonts/GenEiGothicN-U-KL.otf' @ warning/annotate.c/RenderType/960.
```
## 行った対応
```
brew install ghostscript
```

問題は出力の部分であり、入力ではないとみる。なぜならパラメーターを確認する限り日本語であっても問題ないから。
```
  Parameters: {"authenticity_token"=>"4TZ3CoqeWff7wovZrOY/EyMM9xQwxxOShVsPgtald2lvle2jKaNsKVc15EsTWLG0k+rT5LPLmWtnP8S/zSHo1A==", "post"=>{"title"=>"あああああ", "content"=>"aaaa", "desire"=>"", "tag_list"=>""}, "commit"=>"Tweetする（まだツイートされません）", "id"=>"124"}
```

**Comment by ms2sato** [comment]
@shuma1020 

> mogrify: unable to read font `.fonts/GenEiGothicN-U-KL.otf' @ warning/annotate.c/RenderType/960.

単純にこのメッセージだけ読むと `.fonts/GenEiGothicN-U-KL.otf' というパスが見つからない、ではないかなと想像するのですが、パスが合ってないということは無いですかね。

**Comment by shuma1020** [comment]
@ms2sato 
フォントをダウンロードした場所と指定している場所が違うということですか？linuxコマンドでどこにフォントをインストールしているか探しています

**Comment by ms2sato** [comment]
@shuma1020 

> 用いるフォントは日本語に対応しているGenEiGothicN-U-KLでapp/.fontsにあります。

とのことで、それをコード中で呼び出しているんだろうけれど（前に相談受けた時そういうコードだったから）

このファイルのある場所と、呼び出しの箇所で書いているパスがずれていない？という話ね。
相対パスで探されないなら絶対パスで書いてみるととりあえず試すまでいける気がします。相対パス、絶対パスという言葉がわからない場合には調べてみてちょ。

**Comment by shuma1020** [comment]
@ms2sato なるほど！絶対パスにしたらできました！

**Comment by ms2sato** [comment]
@shuma1020 だとすると、`Rails.root.join()` みたいなことをすると、汎用的になる。今の状態だとそのマシン以外で動かせないから。 `Rails.root` を調べてそれで修正すると良いよ。

**Comment by shuma1020** [comment]
@ms2sato 
```
font = Rails.root.join('app').join('.fonts').join("GenEiGothicN-U-KL.otf")
```

ここらの記事を参考にしたのですが、pathnameはパスをオブジェクトとして扱い、それによって汎用性が高まると考えてよろしいでしょうか？
[参考](https://obel.hatenablog.jp/entry/20171129/1511924408)
[参考](https://qiita.com/akkun_choi/items/873c0f4637218c8b8c0e)
[参考](https://docs.ruby-lang.org/ja/latest/class/Pathname.html)

**Comment by ms2sato** [comment]
@shuma1020 理解は合ってますよ

```
Rails.root.join('app/.fonts/GenEiGothicN-U-KL.otf")
```

この表記で大丈夫っすよ。
https://docs.ruby-lang.org/ja/latest/class/Pathname.html
の例を見ると良いと思います。 `/` で区切っているはず。
